# Auto-generated by mtbmcp. Do not edit manually.
import json as _json

SESSION_INFO = _json.loads(r'''{
  "extension_dir": "c:/Users/butch/.vscode/extensions/infineonag.modustoolbox-ai-0.5.0-win32-x64",
  "workspace_path": "c:/mtbfw/graphics",
  "projects": [
    "proj_cm33_s",
    "proj_cm33_ns",
    "proj_cm55"
  ],
  "device_name": "PSE846GPS2DBZC4A",
  "bsp_name": "APP_KIT_PSE84_EVAL_EPC2",
  "board_target": "TARGET_APP_KIT_PSE84_EVAL_EPC2",
  "cy_tools_path": "C:/Users/butch/ModusToolbox/tools_3.9",
  "modus_shell_path": "C:/Users/butch/ModusToolbox/tools_3.9/modus-shell",
  "tcp_port": 62844,
  "ext_port": 62842,
  "pid": 29804,
  "log_level": "info",
  "log_file": "C:/Users/butch/AppData/Local/Temp/mtbai-logs/mtbai.log"
}''')

for _key, _value in SESSION_INFO.items():
    globals()[_key.upper()] = _value

del _json
del _key
del _value
